### ISSUE TITLE
Fortify Security Scan Shows Null Security Key Issue

### ISSUE THREAD

**Issue by slandmann** [suguru03/neo-async#100]
Hi, can you please check?

Encryption keys should never be null and should be obfuscated and managed in an external source. Storing encryption keys, null or otherwise, in plain text anywhere on the system allows anyone with sufficient permissions to read and potentially misuse the encryption key.

Example code where error is thrown:

function createCallback(value, key) {
        return function(err, res) {
          if (key === null) {
            throwError();
          }
          if (err) {
            key = null;
            iterate = noop;
            callback = once(callback);
            callback(err, objectClone(result));
            return;
          }
          if (!!res === bool) {
            result[key] = value;
          }
          key = null;
          if (++completed === size) {
            iterate = throwError;
            callback = onlyOnce(callback);
            callback(null, result);
          } else if (sync) {
            nextTick(iterate);
          } else {
            sync = true;
            iterate();
          }
          sync = false;
        };
      }

**Comment by suguru03** [comment]
I'm not exactly sure what you are talking about, but the keys of `result` won't have `null`.
