### ISSUE TITLE
Callback was already called.

### ISSUE THREAD

**Issue by snnmeatball** [suguru03/neo-async#102]
Starting development server...
66% building 782/834 modules 52 active /Users/snnmeatball/Documents/zhojun/dev/personalCenter/pc/node_modules/core-js/modules/_object-keys.js/Users/snnmeatball/Documents/zhojun/dev/personalCenter/pc/node_modules/neo-async/async.js:16
throw new Error('Callback was already called.');
Error: Callback was already called.
    at throwError (/Users/snnmeatball/Documents/zhojun/dev/personalCenter/pc/node_modules/neo-async/async.js:16:11)
    at /Users/snnmeatball/Documents/zhojun/dev/personalCenter/pc/node_modules/neo-async/async.js:2818:7
    at processTicksAndRejections (node:internal/process/task_queues:75:11)

**Comment by suguru03** [comment]
That's not a library issue. Your code seems to call a callback more than once.
