### ISSUE TITLE
document how generate all files present in npm dist tarball

### ISSUE THREAD

**Issue by pravi** [suguru03/neo-async#111]
package.json only mentions these as files,

"files": [
    "LICENSE",
    "index.js",
    "lib/async.js",
    "lib/async.min.js",
    "dist/async.js",
    "dist/async.min.js"
  ],

but npm dist tarballs has many files, there is no documentation on how to generate those other files and in debian, we need to build from source.

Is this generated using lodash-cli like https://salsa.debian.org/js-team/node-lodash/-/blob/master/debian/rules?ref_type=heads#L14 ?

more https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1064411

**Comment by pravi** [comment]
We did run the gulp task to generate it https://salsa.debian.org/js-team/node-neo-async/-/blob/master/debian/nodejs/build?ref_type=heads#L2 but since package.json#files don't mention it, this was not included in the package. It'd be nice if package.json#files can include it, but now this is enough for the debian package. Thanks to Akshay S Dinesh you figured this out.

**Comment by suguru03** [comment]
I will close the issue since it seems to be resolved.
