### ISSUE TITLE
async v1.0.0 released

### ISSUE THREAD

**Issue by e-jigsaw** [suguru03/neo-async#12]
fyi, async v1.0.0 has been released: https://github.com/caolan/async/releases/tag/1.0.0

I do not know what difference of async v0.9.0..v1.0.0 but, neo-async should update speed comparison and docs.

Thanks

**Comment by suguru03** [comment]
I'm going to update the documentation after doing a performance check using `benchmark.js` and `func-comparator`.
Async v1.0.0 has added feature of `forEachOf`, modified the slice performance and fixed bugs.

I want to update as soon as possible.
thanks!

**Comment by e-jigsaw** [comment]
nice work!

**Comment by suguru03** [comment]
Updated!
https://github.com/suguru03/neo-async#speed-comparison

**Comment by e-jigsaw** [comment]
:+1: :+1: :+1:
