### ISSUE TITLE
Question: Plans to update to be compatible with 1.3.0 of async?

### ISSUE THREAD

**Issue by crowelch** [suguru03/neo-async#13]
I'd be willing to help out.
[changelog](https://github.com/caolan/async/blob/master/CHANGELOG.md)

**Comment by suguru03** [comment]
Thanks for your kindness, I'm very pleased.
I have added `during` and `doDuring` that has same feature and more performance.
I'm going to add `asyncify` and `wrapSync` as soon as possible.

I'm Node.js engineer but I'm not good at English, and I can't write documentation well. :sob:
Would you help me to write document and develop functions?

**Comment by crowelch** [comment]
Yeah I can definitely do that.

I'll get to work on documenting things in the readme

**Comment by suguru03** [comment]
Thank you so much!
I'm going to try my best for development and English.
