### ISSUE TITLE
async.angelFall is much nicer than async.waterfall

### ISSUE THREAD

**Issue by qsona** [suguru03/neo-async#16]
Hi, I read your docs and codes, and now I believe that `async.angelFall` is really good function, which is a good replacement of `async.waterfall` and more robust.
There are many `async.waterfall` in my project but `async.angelFall` is more desirable in many cases, so I decieded to do `async.waterfall = async.angelFall;` :100: 
I appreciate your nice work.
I think that `async.angelFall` should supersede `async.waterfall` in the next major version: i.e. `async.waterfall = async.angelFall`. How do you think of it?
Sorry for my poor English.

**Comment by suguru03** [comment]
Thank you very much for your issue.
I think your idea is very good.
But I'm going to keep it as a drop-in replacement for async, so I would like you to use the `async.angelFall` or `async.waterfall = async.angelFall`.

**Comment by qsona** [comment]
Thanks. Keep up the good work!
