### ISSUE TITLE
waterfall tasks should take callback first

### ISSUE THREAD

**Issue by devinus** [suguru03/neo-async#17]
This would make it so you don't have weird errors where the callback is not where you expected it to be because you got the argument list wrong. Would also allow you to completely ignore arguments for some tasks. Will also allow you to use `async.apply` in the middle of a waterfall.

I've opened this issue in async as well (https://github.com/caolan/async/issues/895), but there might be more of a chance to make an API breaking change here.

**Comment by suguru03** [comment]
`neo-async` has [`angelFall`](http://suguru03.github.io/neo-async/doc/async.angelFall.html) which always takes callback last by using `function.length`.
So you can prevent weird errors if you use it, but it doesn't support `async.apply`.

**Comment by qsona** [comment]
I think you have a point. That is the reason why I like async.angelFall better. https://github.com/suguru03/neo-async/issues/16
On Node.js we often place callback to the last argument so I feel a little uncomfortable if it callback is taken first. But maybe it's not a deep problem because a waterfall task function is hardly reused for other purpose.

Anyway, our code depends on waterfall heavily so the breaking change is not welcome.

**Comment by devinus** [comment]
`angelFall` is a weird name but it's certainly much better. Why is `async.apply` not supportable?

**Comment by devinus** [comment]
Is it because `angelFall` uses `Function.length`? Couldn't you explicitly set that in `apply`?

**Comment by devinus** [comment]
It seems the `length` property on a function is read-only, but you can make a cache of function with specific arities and make the `default` use `new Function` (which is slower).

http://stackoverflow.com/questions/7316688/how-to-programmatically-set-the-length-of-a-function

**Comment by devinus** [comment]
Something like this:

```js
  var functionCache = {};

  function makeFunc(arity, fn) {
    switch (arity) {
      case 0: return function() { return fn.apply(this, arguments); };
      case 1: return function(a) { return fn.apply(this, arguments); };
      case 2: return function(a,b) { return fn.apply(this, arguments); };
      case 3: return function(a,b,c) { return fn.apply(this, arguments); };
      case 4: return function(a,b,c,d) { return fn.apply(this, arguments); };
      case 5: return function(a,b,c,d,e) { return fn.apply(this, arguments); };
      case 6: return function(a,b,c,d,e,f) { return fn.apply(this, arguments); };
      case 7: return function(a,b,c,d,e,f,g) { return fn.apply(this, arguments); };
      case 8: return function(a,b,c,d,e,f,g,h) { return fn.apply(this, arguments); };
      case 9: return function(a,b,c,d,e,f,g,h,i) { return fn.apply(this, arguments); };
      default: {
        if (!functionCache[arity]) {
          var params = new Array(arity + 1).join(',_').slice(1);
          return new Function(
            'fn',
            'return function (' + params + ') { return fn.apply(this, arguments); }'
          );
        }

        return functionCache[arity](fn);
      }
    }
  }
```

**Comment by qsona** [comment]
Probably `Function.prototype.bind` works better.
```
var fn = function(a, b) {}
fn.length // 2
fn.bind(null, 1).length // 1
fn.bind(null, 1, 2).length //0
```

async.apply may be better if this problem is considered (return function with proper `length`.)

**Comment by devinus** [comment]
@qsona I believe that will be significantly slower.

**Comment by suguru03** [comment]
I modified `Neo-Async#apply` to take the `Function#length` for improving convenience. ([test](https://github.com/suguru03/neo-async/blob/master/test/controlFlow/test.apply.js#L45-L106))
Anyway, [`AngelFall`](https://en.wikipedia.org/wiki/Angel_Falls) is the world’s highest waterfall ! :blush: 

![AngelFall](https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/SaltoAngel4.jpg/220px-SaltoAngel4.jpg)

**Comment by devinus** [comment]
I'm going to close this now that `angelFall` does what I need. Thanks @suguru03
