### ISSUE TITLE
Consider discouraging using `async` as import name

### ISSUE THREAD

**Issue by devinus** [suguru03/neo-async#18]
With the rapid inclusion of new version of V8 in Node's renewed development cycle--and ES7 features being rapidly included as well--it makes sense to no longer encourage using `async` as the library's import name as it will soon become a JS keyword.

Perhaps encourage `neoAsync`, `neoasync`, or `nasync` instead?

**Comment by suguru03** [comment]
Thanks for your suggestion.
Its sound good to replace `async` with `neoAsync`.

But I'm going to fix it after [async](https://github.com/caolan/async) make the change on its code because I’m trying to match my sample code same as original [async](https://github.com/caolan/async) as possible.
