### ISSUE TITLE
neo-async 2.0 is incompatible with 1.8

### ISSUE THREAD

**Issue by cvlmtg** [suguru03/neo-async#33]
The result from *detectSeries()* (and I suppose *detect()* and *detectLimit()* too) is different between neo-async 1.8 and neo-async 2.0. here's an example:

```
var async = require('neo-async');

function iterator(obj, done) {
  if (obj.id === 1) {
    done(true);
  } else {
    done(false);
  }
}

var elements = [
  { id: 3 },
  { id: 2 },
  { id: 1 },
  { id: 4 }
];

async.detectSeries(elements, iterator, function(result) {
  console.log(result);
});
```

with neo-async 1.8 this is the output of the script:
```
bash-3.2$ npm --depth=0 ls | grep neo
├── neo-async@1.8.2
bash-3.2$ node test.js
{ id: 1 }
```

with neo-async 2.0 this is the output of the same script:
```
bash-3.2$ npm --depth=0 ls | grep neo
├── neo-async@2.0.0
bash-3.2$ node test.js
true
```

**Comment by suguru03** [comment]
> https://github.com/caolan/async/blob/master/CHANGELOG.md#breaking-changes
> filter, reject, some, every, and related functions now expect an error as the first callback argument, rather than just a simple boolean. Pass null as the first argument, or use fs.access instead of fs.exists. (#118, #774, #1028, #1041)

Async v2 and Neo-Async v2 were changed. The first argument always takes an error.
So you have to change as following.

```js
function iterator(obj, done) {
  if (obj.id === 1) {
    done(null, true);
  } else {
    done(null, false);
  }
}
```

**Comment by cvlmtg** [comment]
then you have to fix the doc. I checked neo-async doc on http://suguru03.github.io/neo-async/doc/async.detect.html  and it says:

```
// array (not use error handling)
var iterator = function(num, done) {
  setTimeout(function() {
    order.push(num);
    done(num % 2); // <------ here
  }, num * 10);
};
```

there is just one argument for the callback. You can't expect users of you library to read the documentation of another one.

**Comment by suguru03** [comment]
Oh, I'm sorry I forgot to fix them. 
Thank you for pointing it out, I'll fix soon.

**Comment by cvlmtg** [comment]
thanks!
