### ISSUE TITLE
Integration into async in the future?

### ISSUE THREAD

**Issue by bid** [suguru03/neo-async#4]
What are the long-term plans for neo-async? Is it supposed to stay an own project or will you strive for integration into async in the future?

**Comment by suguru03** [comment]
> What are the long-term plans for neo-async?

I have many plans for improvement of convenience. I'm going to make a roadmap.

> Is it supposed to stay an own project or will you strive for integration into async in the future?

The code structure of Neo-Async is far from Async now, so it could not be merged anymore. I will support on my project.
