### ISSUE TITLE
Readme error

### ISSUE THREAD

**Issue by pitaj** [suguru03/neo-async#5]
I think under the server side result you meant to write neo-async/a sync for the radio, not async/neo-async

Otherwise this implies that neo-async is way shower, wench I don't think is true.

**Comment by pitaj** [comment]
Also, you should add an image such as this one to the readme:

![neo from the matrix](https://ianthestorck.files.wordpress.com/2013/08/neo.jpg)

**Comment by pitaj** [comment]
Sorry, like this one:

![bullet time neo](http://cdn.virtualthreat.com/wp-content/uploads/2012/05/Bullet-time.jpg)

**Comment by suguru03** [comment]
Sorry for my bad English.
I had made a mistake in README , the "average speed" should be "average time".
I also think that (neo-async / async) is easier to understand, will fix it later.
Thanks for the correction!

By the way, This image is very interesting! :penguin:
