### ISSUE TITLE
Missing LICENSE file in npm package

### ISSUE THREAD

**Issue by char0n** [suguru03/neo-async#59]
Hello, is it possible to incorporate the LICENSE file inside the npm package ? Now it's missing. It's implied by MIT license that if licensed under the MIT the source code must be accompanied by full license text. If the license file is not in the npm package a lot of people cannot use it.

Thank you

**Comment by suguru03** [comment]
@char0n @opichals Sorry for the late reply.
I just published it on v2.5.2. Thanks for your issue. 😄

**Comment by char0n** [comment]
Thanks a lot
