### ISSUE TITLE
Can i switch directly from async to neo-async

### ISSUE THREAD

**Issue by Pana** [suguru03/neo-async#6]
I have test neo-async with async test case, it didn't pass. I know there may be some test case relate to detail logic, so it didn't pass.

**Comment by Pana** [comment]
Just want to make sure i can switch directly

**Comment by jedireza** [comment]
From the README:

 > Neo-Async is thought to be used as a drop-in replacement for Async, it fully covers its functionality and runs faster

Obviously you'll want to test it out in your app to see how it works for you.

**Comment by suguru03** [comment]
Basically Neo-Async covers Async functionality but there was some performance issue inside `waterfall`'s original implementation.
I rewrote it and removed codes like `setImmediate` to boost the performance, so the detail logic may differ from Async.
I'm glad if you could provide any other test case.

I fixed some bugs which maybe related to your async test case. https://github.com/suguru03/neo-async/commit/758b0de31e9804d37b58cad232c0d54097121728 https://github.com/suguru03/neo-async/commit/ff3d78879ef75ced30b8917a75ee85d829000e6d

**Comment by suguru03** [comment]
@Pana 
I apologize for it.
I fixed source code to pass whole of the Async tests case on v0.6.x.
Could you please check your test case?

**Comment by Pana** [comment]
I have test new neo-asyn on async test, it has all pass, great.
