### ISSUE TITLE
possible error in the retry() function

### ISSUE THREAD

**Issue by cvlmtg** [suguru03/neo-async#62]
https://github.com/suguru03/neo-async/blob/b449ec0cc5dc15ccf8cc2592900f6a4d7b97af20/lib/async.js#L8355

shouldn't it be `case 'function'` ?

**Comment by suguru03** [comment]
Hi @cvlmtg !
https://github.com/suguru03/neo-async/blob/b449ec0cc5dc15ccf8cc2592900f6a4d7b97af20/lib/async.js#L21
Yes, it is. 🙂
