### ISSUE TITLE
FYI: "event-stream" dependency is backdoored, apparently starting from v3.3.5

### ISSUE THREAD

**Issue by vladimiry** [suguru03/neo-async#66]
https://github.com/dominictarr/event-stream/issues/116

**Comment by suguru03** [comment]
Thanks for the information!
It doesn't have any dependencies, it should be fine.
I'll deal with the dev dependencies, thanks :)

**Comment by vladimiry** [comment]
Also if someone is interested, preliminary analysis:
- https://github.com/dominictarr/event-stream/issues/116#issuecomment-441749105
- https://github.com/dominictarr/event-stream/issues/116#issuecomment-441759047
- https://github.com/dominictarr/event-stream/issues/116#issuecomment-441759442

**Comment by suguru03** [comment]
There were some out-dated tasks so I removed all event-stream dependencies. 😄
