### ISSUE TITLE
difference  between angelfall and waterfall

### ISSUE THREAD

**Issue by ORESoftware** [suguru03/neo-async#67]
Just wondering if there is a difference between async.angelfall and async.waterfall

async.cascade is also a good name, by the way.

**Comment by ORESoftware** [comment]
bump

**Comment by suguru03** [comment]
[`angelFall`](http://suguru03.github.io/neo-async/doc/async.angelFall.html) injects callbacks into the last arguments, each function doesn't rely on the previous callback.

FYI, Angle Fall is the highest waterfall, my friend named it. 😉 
https://en.wikipedia.org/wiki/Angel_Falls
