### ISSUE TITLE
Does it support ie 11?

### ISSUE THREAD

**Issue by cekvenich** [suguru03/neo-async#70]
ie 11 support?

**Comment by suguru03** [comment]
Hi, @cekvenich !
I haven't tested yet, I will test it soon. 🙂

**Comment by suguru03** [comment]
@cekvenich 
Sorry for the late reply.
I tested several test cases on IE11 on the IE tab. It seems working well 😄 

If you find any issues, please let me know!

**Comment by cekvenich** [comment]
thx! will be using it.
