### ISSUE TITLE
Important - Avoid Array.prototype.shift/unshift

### ISSUE THREAD

**Issue by ORESoftware** [suguru03/neo-async#74]
I looked through the codebase, it seems that there are a lot of references to Array.prototype.shift.

The problem with shift/unshift is that they go through the whole array and update the indices.
In short,  pop/push is O(1), but shift/unshift are O(N). See:

```js
{
  
  const size = 100000;
  const v = new Array(size).fill(null);
  
  const shiftStart = Date.now();
  
  for(let i = 0; i < size; i++){
    v.shift();
  }
  
  console.log('shift time:', Date.now() - shiftStart);
}


{
  const size = 100000;
  const v = new Array(size).fill(null);
  
  const popStart = Date.now();
  
  for(let i = 0; i < size; i++){
    v.pop();
  }
  
  console.log('pop time:', Date.now() - popStart);
}

```

you will see this output:

> shift time: 933
> pop time: 1

You should strive to use a linked-list for queues instead of a simple JavaScript array.
A linked-list can do things in constant time etc.

The difference in performance is mostly noticeable for very large arrays, but if you want to squeeze performance, this is a good place to do so.

**Comment by suguru03** [comment]
@ORESoftware Thanks for the issue!
https://github.com/suguru03/neo-async/blob/master/lib/async.js#L7827
https://github.com/suguru03/neo-async/blob/master/lib/async.js#L8055
https://github.com/suguru03/neo-async/blob/master/lib/async.js#L8328

I see three places which `Array#shift` is used.
The last one, we could replace it with a linked-list, I'm not sure the others. I always welcome PRs! 😄
