### ISSUE TITLE
webpack deprecation warning

### ISSUE THREAD

**Issue by amirHossein-Ebrahimi** [suguru03/neo-async#92]
Hi, here I faced new deprecation warning  
```bash
[DEP_WEBPACK_TEMPLATE_PATH_PLUGIN_REPLACE_PATH_VARIABLES_HASH] 
DeprecationWarning: [hash] is now [fullhash] (also consider using [chunkhash] or [contenthash], 
see documentation for details)
```

occurred at `arrayEach` in (node_modules/neo-async/async.js:2405:9)

Thanks:pray:

**Comment by suguru03** [comment]
@amirHossein-Ebrahimi Thanks for the issue!

That's not a neo-async issue.
Does it seem this? If you don't know, please ask these questions on StackOverflow.
https://webpack.js.org/configuration/output/#template-strings
